### ISSUE TITLE
Error occured when we tried to run server

### ISSUE THREAD

**Issue by jarvis08** [stanford-oval/SPL#1]
We are trying to give natural language input to Almond server's `conversation`, and see the response.

## 1. Environments

We tested on Ubuntu 18.04 & OS X Catalina.
- Installed node 10.22.0 with nvm
- Installed yarn 1.22.5 with npm
- Installed python3.6, cloned genienlp, and installed genienlp with pip.
- Cloned repositories(genie-toolkit, thingtalk, thingengine-core, almond-server)
- Installed packages with the command `yarn`
- Linked repositories with the command `yarn link`
- Downloaded models you shared us before
- Located model to ../SPL/restaurants/models/en/best.pth.

### 2-1. Run NLU model

We moved to the SPL repo's directory, and used commands below.

```
$ export experiment=restaurants
$ export nlu_model=en
$ export server_locale=en
$ make ${experiment}/${nlu_model}/run_server
```

### 2-2. Run almond-server

We moved to the almond-server repo's directory, and used commands below.

```
$ export THINGENGINE_HOME=/Users/jarvis08/Documents/10_Organs/02_HYU/DBSL/Almond/thingengine-core
$ export THINGENGINE_NLP_URL=http://127.0.0.1:8400
$ cd path_to_server/almond-server
$ node main.js --locale en
```
## 3. Errors we got

We successfully  ran the both servers, signed in the almond page(3000), and started `conversation`.

We tried 3 types of inputs.
- The 1st input is a natural language sentence from the evaluation dataset of en model.
- The 2nd input is the thingtalk with `\t`, corresponding to the 1st nl input.
- The 3rd input is the cat api's command. It didn't make any error, and we expected almond to return an image of a cat, but we could only get the url of it.

![image](https://user-images.githubusercontent.com/42799660/92234570-3f9af080-eeed-11ea-8a93-abcd55b604d6.png)

### 3-1. Error for the almond-server(3000)

In the first image, the error messages were generated by the 1st input above(NL input).

![image](https://user-images.githubusercontent.com/42799660/92237443-53952100-eef2-11ea-896c-7f42fb6131c6.png)

Next image is the error for the 2nd input.

![image](https://user-images.githubusercontent.com/42799660/92237494-6c9dd200-eef2-11ea-84ba-1ba78126cc32.png)

### 3-2. Error for the genie-toolkit(8400)

genie-toolkit couldn't understand the 1st input(NL sentence), and generated the 400 error in the last line of the image below.

![image](https://user-images.githubusercontent.com/42799660/92237729-d61de080-eef2-11ea-81c4-8baaffe686d9.png)

We want to  check right response from natural language inputs, which make 400 errors.

Thank you Mehrad.

**Comment by Mehrad0711** [comment]
Issue is addressed in this [post](https://community.almond.stanford.edu/t/how-to-enroll-another-language-thingpedia-device/380).
